moleculerjs/moleculer-web

CHANGELOG.md, README.md, examples/full/index.js, package.json, src/errors.js, src/index.js, test/unit/index.spec.js
It is possible to use named parameters in aliases. Named parameters are defined by prefixing a colon to the parameter name (`:name`)
**Usage**
```js
broker.createService(ApiGatewayService, {
settings: {
routes: [{
path: "/api",
aliases: {
"GET greeter/:name": "test.greeter",
"optinal-param/:name?": "test.echo",
"repeat-param/:args*": "test.echo",
"GET /": "test.hello"                
}
}]
}
});
// Start server
broker.start();
```
Example: [examples/full](/examples/full)
=> Named parameter in aliases

package-lock.json, package.json, src/index.js, test/integration/index.spec.js
While trying to expose a `moleculer-db` service through the API gateway I noticed there is no way to pass the `query` param to the services `list` action ([doc](https://github.com/moleculerjs/moleculer-db/tree/master/packages/moleculer-db#parameters-2)). The service expects the `query` param to be of type `object` but nested objects are not supported by node's `querystring` module (see https://github.com/nodejs/node-v0.x-archive/issues/1665).
This PR replaces `querystring` with [`qs`](https://github.com/ljharb/qs), which supports nested objects.
**Example Request:**
`GET /users/list?query[name]=Peter` 
**Before** (using [`querystring`](https://nodejs.org/api/querystring.html) module): 
`params: { "query[name]": "Peter" }`
**After** (using [`qs`](https://github.com/ljharb/qs) module): …
=> Support nested objects in query params

index.d.ts
This fixes the TS definition to make it possible to do:
throw new ApiGatewayService.Errors.UnAuthorizedError(...);
as seems to be the intent going by the JS implementation.
The previous TS definition meant that ApiGatewayService.Errors.UnAuthorizedError etc. were instances of those error types, not the constructor functions for those types.
=> fix type definition of Errors

examples/full/index.js, src/index.js, test/unit/service/httpHandler.spec.js
* adds a new setting `log4XXResponses`. Default is true for backwards compability
* when `log4XXResponses` is set to false and an action rejected with a 4XX status code, the error will not be logged on error level (refer to https://github.com/moleculerjs/moleculer-web/issues/76)
* adapts the full example to include setting this option for documentation purpose
* adds unit tests for the `httpHandler` method
=> Do not log 4XX error responses if configured

package-lock.json, package.json, src/index.js, src/utils.js, test/integration/index.spec.js, test/services/test.service.js
=> Auto generate ETag & freshness check

src/index.js, test/integration/index.spec.js
I've noticed that the first `~` character in the request URL path is replaced by a `$` character. I assume this exists to support calling actions exposed by the internal `$node` service (see [here](https://moleculer.services/docs/0.13/services.html#Internal-services)), eg. `GET /~node/list` is calling the action `$node.list`. 
In our case this causes problems because we have a service exposing database records (using `moleculer-db`) containing a `~` in their ID and use the following alias:
```js
aliases: {
'GET contacts/:id': 'contacts.get'
}
```
When calling `GET /contacts/ABC~123`, the `params.id` is `ABC$123` instead of `ABC~123`.
I've changed the regex to only replace the tilde from the beginning of the path, but I'm not sure if this breaks some other feature I might have missed.
=> Replace ~ only at the beginning of URL path (eg. "~node")

src/index.js
When an error has a code not in range 400 to 500 the res.writeHead(code) throws a RangeError and become a unhandled rejection and api gateway don't response at all
**Example error:**
`MongoError { code: 11000, message: E11000 duplicate key error collection: database.users index: email_1 dup key: { : \"name@example.com\" }}`
=> Validate error code range on send error

src/index.js
If you setup a service in this way:
```
module.exports = {
name: 'api',
mixins: [
MoleculerWeb
],
settings: {
path: '/',
routes: [{
path: '/users',
mappingPolicy: 'restrict',
aliases: {
'REST /': 'users'
}
}]
}
};
```
The inferred aliases will be wrong. This is what will be logged in console:
> GET /users => users.list
> GET /users//:id => users.get
> POST /users => users.create
> PUT /users//:id => users.update
> PATCH /users//:id => users.patch
> DELETE /users//:id => users.remove
With the proposed fix, the aliases will be correctly generated. This is the new logged lines:
> GET /users => users.list
> GET /users/:id => users.get
> POST /users => users.create
> PUT /users/:id => users.update
> PATCH /users/:id => users.patch
> DELETE /users/:id => users.remove
=> Fix REST shorthand alias setup

package-lock.json, package.json
This PR adds `bluebird` as an explicit package dependency because it is used by `utils.js`.
`moleculer`, a peer dependency of `moleculer-web`, has a dependency on `bluebird`. This means that `moleculer-web` will find `bluebird` if it's installed in the `node_modules` root, which is probably what is currently happening in many installations. However, if multiple packages target different versions of `bluebird`, `npm` will remove `bluebird` from the `node_modules` root and instead nest the installation inside the parent package directory, thus making it unavailable to `moleculer-web`. Packages should declare any dependencies they use and not rely on implicit dependencies of dependencies to be available.
=> add explicit bluebird dependency

src/index.js, test/integration/index.spec.js, test/services/test.service.js
Currently, we can define/change `basePath` only on service level using `service.settings.rest`. This PR will add an option to define action-specific `basePath`.
=> Add option to change `basePath` on action level for AutoAliases

src/index.js, test/integration/index.spec.js
The service now has an encodeResponse method which replaces
the direct calls to JSON.stringify() in sendResponse / sendError.
The encodeResponse method can be overriden by the user and takes the
req/res objects so that headers can be inspected and the correct
encoding can be used.
=> Add encodeResponse method

src/index.js
After logging a call's response, an empty message gets logged. This looks fine in a console logger, but when json logs are streamed to an aggregation service (e.g. Datadog) this empty log is unnecessary and meaningless noise. This PR removes it.
=> remove empty log

src/utils.js
Class constructor BadRequestError cannot be invoked without 'new'.
```
TypeError: Class constructor BadRequestError cannot be invoked without 'new'
at decodeParam (/app/node_modules/moleculer-web/src/utils.js:25:9)
at Alias.match (/app/node_modules/moleculer-web/src/alias.js:108:23)
at Object.resolveAlias (/app/node_modules/moleculer-web/src/index.js:1103:27)
at Object.handler (/app/node_modules/moleculer-web/src/index.js:198:24)
at /app/node_modules/moleculer/src/utils.js:131:22
at ServiceBroker.timeoutMiddleware (/app/node_modules/moleculer/src/middlewares/timeout.js:35:14)
at ServiceBroker.fallbackMiddleware (/app/node_modules/moleculer/src/middlewares/fallback.js:29:11)
at ServiceBroker.errorHandlerMiddleware (/app/node_modules/moleculer/src/middlewares/error-handler.js:14:10)
at …
```
=> Class constructor BadRequestError cannot be invoked without 'new'.

.travis.yml, src/index.js, test/integration/index.spec.js, test/services/multiRoute.service.js, test/services/test.service.js
In my application I need the possibility to define several REST routes for a service. With this change it is possible to define an array of routes.
```
settings: {
rest: ["/route", "/route/multi"]
},
actions: {
test: {
rest: "GET /test"
...
}
}
```
Both routes ```/route/test``` and ```/route/multi/test``` call the specific action.
=> added multiple REST routes in service settings

src/index.js, test/integration/index.spec.js
This fixes a bug where the route's aliases were not replaced on route update. The object stored in the alias's `route` property is the old route, which was being compared to the newly created route using object equality.
=> fix: clean old aliases on route update

src/index.js
Hello!
I noticed some excessive logs with implementations that refresh their routes and aliases constantly. To avoid that issue, I wrote this PR to create a configuration, similar to `logResponse` or `logRequestParams` but targeted to the route registration logger calls.
=> feat: create configuration for the route registration logging process

.eslintrc.js, .vscode/launch.json, examples/file.service.js, examples/file/assets/index.html, examples/file/index.js, src/alias.js, src/index.js, test/integration/index.spec.js
**Changes**
Access to the URL parameters (`/upload/:id`) via `ctx.meta.$params`. 
In the previous version only at `stream`-typed aliases, the `ctx.params.$params` works but only if the target service was on the same node as API gateway because the `params.$params` is not transferred. At multipart file upload, this doesn't work in any way.
**TODO**
=> Fix url params to transfer at streaming

.gitignore, src/index.js, test/integration/index.spec.js
=> set default when bodyParser is true

src/index.js
allow to change default `500ms` at [line 1583](https://github.com/moleculerjs/moleculer-web/blob/master/src/index.js#L1583), that will be called at [line 1529](https://github.com/moleculerjs/moleculer-web/blob/master/src/index.js#L1529)
=> allow set debounceTime

src/index.js, test/unit/service/httpHandler.spec.js
This change allows users to override or disable the default logging behaviour when errors are encountered.
=> Move default error logging behaviour to errorHandler method

.vscode/launch.json, CHANGELOG.md, examples/dev/index.js, src/index.js, test/integration/index.spec.js
Many developers issued that version 0.10 doesn't support multiple routes with the same path. This version fixes it but you should give a unique name for the routes if they have same path.
**Example**
You can call `/api/hi` without auth, but `/api/hello` only with auth.
```js
const ApiGateway = require("moleculer-web");
module.exports = {
mixins: [ApiGateway],
settings: {
path: "/api",
routes: [
{
name: "no-auth-route", // unique name
path: "/",
aliases: {
hi: "greeter.hello",
}
},
{
name: "with-auth-route", // unique name
path: "/",
aliases: {
"hello": "greeter.hello",
},
authorization: true
}
]
}
};
```
=> Add named-routes

src/index.js
A simple suggestion to configure `rateLimit` in route level.
```js
const ApiGateway = require('moleculer-web')
module.exports = {
name: 'api',
mixins: [ApiGateway],
settings: {
rateLimit: rateLimitGlobalConfig,
routes: [
{
path: '/withLocalRateLimit',
// now you can pass rateLimit here
// it will override the global rateLimit
rateLimit: rateLimitConfig,
aliases: {
'GET /2': 'test.2'
}
},
{
path: '/withGlobalRateLimit',
aliases: {
'GET /1': 'test.1'
}
}
]
}
}
```
If you like the suggestion, I can create relevant tests
resolve #18
=> rateLimit in routes level

examples/multi-auth/index.js, src/index.js, test/integration/index.spec.js
This PR adds feature to define custom authentication and authorization methods for every routes. In this case you should set the method name instead of `true` value.
**Example**
```js
module.exports = {
mixins: ApiGatewayService,
settings: {
routes: [
{
path: "/aaa",
authentication: "aaaAuthn",
authorization: "aaaAuthz",
aliases: {
"GET hello": "test.hello"
}
},
{
path: "/bbb",
authentication: "bbbAuthn",
authorization: "bbbAuthz",
aliases: {
"GET hello": "test.hello"
}
},
{
path: "/ccc",
authentication: true,
authorization: true,
aliases: {
"GET hello": "test.hello"
}
}
]
},
methods: {
aaaAuthn() {
this.logger.info("Called 'aaaAuthn' method.");
},
aaaAuthz() {
this.logger.info("Called 'aaaAuthz' method.");
},
bbbAuthn() {
this.logger.info("Called 'bbbAuthn' method.");
},
bbbAuthz() { …
```
=> Multi authentication & authorization for routes

src/index.js
Hi,
When autoAliases is set to true, a moleculer fails to start if it is clustered with moleculer java, this is caused by java services not expossing settings.rest since they may not be aware of moleculer web(js). thanks.
=> skip services without settings

examples/multi-auth/index.js
In context, this line would need to reference /ccc rather than /bbb
This might have been a copy/paste/forget error
=> Fix to comment in multi-auth example

src/index.js, test/integration/index.spec.js
Add `alias` to the following hooks as last parameter:
- `onBeforeCall`
- `authentication`
- `authorization`
You can access it in the hook handlers, e.g.:
```js
{
path: "/",
onBeforeCall(ctx, route, req, res, alias) {
ctx.meta.aliasPath = alias.path;
}
}
```
=> Add alias as last parameter

src/index.js, test/integration/index.spec.js, test/unit/service/httpHandler.spec.js
If we use assets, and send OPTIONS(preflight) request for this assets
Its will return 404 because of its not match any action.
=> Fix cors problem in assets

examples/test.service.js, src/index.js
Fix #288 
Sending `$api.aliases.regenerated` event after regeneration executed.
=> Broadcast event after alias regeneration

src/index.js
Resolves #298.
Added handlers to handle `error` and `close` events on response and resolve/reject respectively the context caller.
=> fix: #298: register on close and error event on response

src/index.js
Hello,
this PR to change the "close" event handler from reject to resolve in order to make the promise end with no errors.
When a http requested is issued and then cancelled by the client the "finish" event is not triggered (https://nodejs.org/docs/latest-v16.x/api/http.html#event-close_1)
Thanks!
=> fix: resolve promise when close event is fired for res

src/index.js
Fixes https://github.com/moleculerjs/moleculer-web/issues/206
In node.js versions < v18 this was set to 0 (meaning disabled).
However, in the docs it is stated that:
> It must be set to a non-zero value (e.g. 120 seconds) to protect against potential Denial-of-Service attacks in case the server is deployed without a reverse proxy in front.
In node.js v18 the default value is `300000` ms = 5 minutes,
This PR uses node.js v18 default value
=> add default reqTimeout

index.d.ts
Add some properties set on `IncomingRequest` by `moleculer-web`. 
I had looked at adding `locals` to `GatewayResponse` as well though held off as it seemed primarily internal. Would it be worth adding?
=> add `originalUrl`, `parsedUrl`, and `query` to request typing

src/index.js, test/integration/index.spec.js, test/services/test.service.js
The `Location` header is _also_ used by the `201 Created` status code.  But the currently logic filters out the information provided in `ctx.meta.$location` if I return `ctx.meta.$statusCode = 201`.  This should not happen.  The `Location` header is essential in a `201 Created` response.  I've changed to logic so that `201` is included in the status codes that passthrough `ctx.meta.$location` to the `Location` header.
=> fix: add 201 Created to status codes

package-lock.json, package.json
Changes:
- chore(depdencies): update qs package to mitigate CVE-2022-24999
Notes:
https://github.com/advisories/GHSA-hrpp-h998-j3pp
=> update qs package to mitigate CVE-2022-24999

index.d.ts
When logging `req` and `res` from middleware functions the output does not match `IncomingMessage` and `ServerResponse` from `node`. Instead they seem to match moleculers extensions of these types: `ÌncomingMessage` and `GatewayResponse`.
=> fix: correct types for route middleware functions

index.d.ts
May be missing something here but I cannot find any other references to `callingOptions` and suspect it may be a typo.
=> fix: incorrect key for calloptions type

index.d.ts, src/index.js, test/integration/index.spec.js, test/services/test.service.js
Closes https://github.com/moleculerjs/moleculer-web/issues/309
=> feat: add support for qs options

examples/sse/assets/index.html, examples/sse/assets/index.js, examples/sse/assets/style.css, examples/sse/chat.service.js, examples/sse/index.js
Added a simple example of a chat using SSE, which was asked about in #228 .
The application is available on the localhost: 3000 after launch.
=> SSE Example with simple chat

package-lock.json, src/index.js, test/integration/index.spec.js, test/services/test.service.js
Header assignments with invalid characters now don't lead to a gateway crash.
* fixes [Issue #323](https://github.com/moleculerjs/moleculer-web/issues/323)
* dependencies update
=> fix: secure header assignment to avoid process crash

src/index.js
See the documentation on pipe: https://nodejs.org/api/stream.html#readablepipedestination-options
> One important caveat is that if the Readable stream emits an error during processing, the Writable destination is not closed automatically. If an error occurs, it will be necessary to manually close each stream in order to prevent memory leaks.
On the current version this leads to responses hanging on both the server and the browser.
With this change, this leads to the browser seeing an error (with interrupted stream).
=> Avoid stream hanging on error

index.d.ts
- change `export type` to `export interface` due to `error TS4082`
- remove non-exported `IncomingRequest`, `GatewayResponse` from `export default`
=> imp(index.d.ts): correct export ts types

index.d.ts
`settings.server` can be:
- `null`/`false`/`true`: currently defined
- `net.Server` if created by `http.createServer` or any class that extended
- `tls.Server` if created by `https.createServer`, `http2.createServer`, `http2.createSecureServer` or any class that extended
=> imp(index.d.ts): correct server type

src/index.js
We have problem with our request logs. Wasn't able to reproduce it in a test but for some reason the request log gets cropped (we don't get the full url). The response log is always correct and I noticed that the `req.originalUrl` is used for the response. Using the same url in both response and request seemed reasonable.
=> fix: request url not logged correctly

test/unit/service/httpHandler.spec.js
Started refactoring some test while working on my other PR. No change in the test, just restructured them and created common setup methods to make it easier to add new tests in the future.
=> refactor: simplify http handler test with reusable setup functions

index.d.ts
`satisfies` issue:
```typescript
export default {
name: 'gateway',
mixins: [ApiGateway],
.......
} satisfies IServiceSchema<ServiceSettingSchema>;
```
=>
```typescript
TS4082: Default export of the module has or is using private name ApiGatewayErrors
TS4082: Default export of the module has or is using private name RateLimitStores
```
=> Update index.d.ts - export RateLimitStores/ApiGatewayErrors

.github/workflows/nodejs.yml, README.md, index.d.ts, src/index.js, test/integration/index.spec.js
moleculer web already has a whitelist option for the auto alias functionality, but it lacks a blacklist functionality.
In which use case is this needed?
We have multiple services that act as gateways, each mapped to a different subdomain and each of them should only list relevant routes, doing this with whitelist becomes extremely cumbersome when you create more than a handful of services.
=> feat: added blacklist functionality for auto aliases
